// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ODataProject.Context;

namespace ODataProject.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20190711002258_SeedingData002")]
    partial class SeedingData002
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ODataProject.Models.School", b =>
                {
                    b.Property<Guid>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.HasKey("SchoolId");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            City = "Mexicali",
                            Name = "UABC - Mexicali",
                            State = "Baja California"
                        },
                        new
                        {
                            SchoolId = new Guid("a5c63668-6dd7-421a-98f7-795862054eea"),
                            City = "Mexicali",
                            Name = "TECNOLOGICO UNIVERSIDAD - Mexicali",
                            State = "Baja California"
                        },
                        new
                        {
                            SchoolId = new Guid("69636bb0-c211-4e83-bbed-d6b7682bd6c9"),
                            City = "Ensenada",
                            Name = "UABC - Ensenada",
                            State = "Baja California"
                        },
                        new
                        {
                            SchoolId = new Guid("ed5331c6-3cef-46b3-9b34-c23a19dccc80"),
                            City = "Mexicali",
                            Name = "XOCHICALCO UNIVERSIDAD - Mexicali",
                            State = "Baja California"
                        },
                        new
                        {
                            SchoolId = new Guid("4172f41d-f7a3-4db9-bdb3-4b7709a31831"),
                            City = "Mexicali",
                            Name = "CETYS UNIVERSIDAD - Mexicali",
                            State = "Baja California"
                        },
                        new
                        {
                            SchoolId = new Guid("c80f1741-b017-4ff7-87f6-d48c8f326fdc"),
                            City = "Tijuana",
                            Name = "CETYS UNIVERSIDAD - Tijuana",
                            State = "Baja California"
                        });
                });

            modelBuilder.Entity("ODataProject.Models.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<Guid>("SchoolId");

                    b.Property<int>("Score");

                    b.HasKey("StudentId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("71a8ab9e-d7ca-4d8e-9a2d-dd5e573ac853"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("6cf35254-a385-4457-96e4-ee6f10b9c306"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("b7035118-abff-4262-b5a6-8a2e1e44ef6b"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("3a2f4d0d-97f6-475d-9f1f-7e522d7a199f"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("68cbdc50-3d13-456d-b61a-919bea62fa12"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("a3f038cf-a74c-4ce8-8a16-267263e6b748"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("2242d119-a26d-4531-b640-45c97848dd0f"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("256fd748-ca30-48f8-90a5-d18346526d27"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("9ec31dc0-60ca-425e-938b-acbad8e3df46"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("6531918c-1553-45fd-86a5-ffe8ec014bae"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("13ca4336-39eb-4746-8eea-b1d2954a5986"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("64b53884-59d1-41f7-80fb-ac0831281b76"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("e078145d-5ce9-4ef8-96a0-ee42bd36c550"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("16da7ab2-17d8-4000-8965-2506bf0a931e"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("70a34efd-93d6-40f8-b84f-1712954cfd71"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("501d58de-528d-49cd-87db-e9b12d9da6bc"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("587897bb-c675-4699-be71-b2f8a2796ca9"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("0277e8b7-ec32-4fc4-b017-e644a77f1b2c"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("e1f7ec4f-df2f-4e43-8eb4-7e5dae6e8f8d"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("50d0ddfc-a996-4e6f-87f9-08873005b799"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("9fd013ad-6d06-49e7-bd4b-9a8de838c185"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("bf2354ff-2829-4fb6-9e15-93f1c8db8790"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("d41e5c7f-fb7b-4533-b8d0-bcb1f32c8e32"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("2d9000c8-a723-4645-9adb-ac87c8e77f84"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("c5219878-1c10-456d-aad3-ae89c6d22f20"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("e49ebdb3-a411-486c-8770-9d061a4a66e5"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("bb79b7a4-c00f-45f2-85b2-3e5efa8e60dd"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("ea3a0a8b-7399-4d63-8414-7dd9e7913909"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("f4565d0f-114b-4ba3-9594-3177f390ebc6"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("8a419eed-440a-4cf2-92c5-6210ed1ba56a"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("b790ef25-a5b9-4c2b-bce6-d8b999e5a79c"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("753d3adb-c3a5-4745-ae58-26901da322fa"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("0b963e83-82c9-455f-b6e1-ec15efd5a123"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("7013b1fb-39f9-4051-abbf-b9319f5ff96f"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("6a71eabe-0d36-49b0-b74b-e04272bfdd81"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("9ba6a968-b467-4cfa-ae7d-795cc31e75ca"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("7dde5c5c-6b1e-4d48-9aff-2ee32cdc10e8"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("2beb4b83-3554-449f-9ffa-fb7f69874d7e"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("133a177c-558d-413f-9b0e-0a9cb32e41b5"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("7376c8ee-c5a8-42a2-bbfb-044831d0c30c"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("5a47f162-d30c-4f9c-9f6c-c6c4a834f16c"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("976ddae6-d479-4356-ae9a-6f005fbd0be0"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("5d700fac-f890-4880-ad4d-ae54301b842a"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("a676aef6-6238-461d-87ee-be361ef3f9b4"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("af9d3c50-bbd4-4cd8-97c4-f71a5a3fd302"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("aa71c5ef-4fc3-4744-94a2-f717d298b431"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("314bd449-4ab2-42df-a661-b7314a779d24"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("91285bfc-f2ca-411c-9e44-e02d176868dc"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("d63d1007-293b-4ff9-8cc3-9c8a4d5214e6"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("67bd2bd5-2a92-4c2f-b067-730ed48d3720"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("11ab4b0a-b59f-4cb3-9280-df680e5072d4"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("40d093c5-b2bf-417c-8cc0-494dca63300a"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("0c1cd051-56f8-4afd-a2ed-b0b37b2ae3cb"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("717ebb7b-f24d-4b81-96cc-546fb0691117"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("f168dc03-3842-4e14-a7ee-d32d0c5a87f3"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("15b01b1d-b026-4718-ac70-8cdae5974b42"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("e1de7ce1-1834-469f-9d9d-59fa0a11a7d7"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("4ee98f82-6535-4207-a56a-f80b491782eb"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("e65539a4-68cc-48ea-be47-07f8340c3097"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("5b95cc0b-0c33-4437-a2d6-774b214c0bd0"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("8d5d42d4-ce00-4f7d-9414-632aa38d86f4"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("31d35fe0-630d-41f7-9dd8-86c97fd40ee9"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("a1bb89de-af33-404b-9ab7-758aa0e4b571"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("1eced42d-4322-400c-a10b-a65f029e56d7"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("9434ff19-d8a4-48df-9d8a-8bff8425ff7a"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("0e09ccda-ee21-4be8-9762-a4b46c535621"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("2b3f393b-b68a-4ded-97c4-036998612fdc"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("62406b6a-746a-47c5-a9e4-cc853d55fe0d"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("19878e3d-94d9-4a2e-a483-344e5b09e847"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("49e7076e-b9ac-4c5f-b7c0-5e7d0f813814"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("d2f45bc7-db47-4744-aed2-edfc5f0a4ab5"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("b7768a0e-d84a-4b15-8a32-061ded7c003e"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("27eb8880-2c6c-48fa-9c83-aa77b478884b"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("4ad160da-564d-4f49-8c21-d9fc6343f9df"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("e8d8fe1e-1c32-4cc0-8eb6-84433d7b7a62"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("01b355bc-ad47-4d65-a5bb-736a18168534"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("ad768339-8a0d-469f-b3e7-4097b89138d6"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("98bad47e-5f0a-4267-9e54-ab5f9ff36428"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("098efda6-b3da-42bb-bc44-f6c159ca99ae"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("013e31e5-b97a-4147-847e-7d22941e62f8"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("6b57356f-7c0d-483d-ae3f-23e8e0d3efc2"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("5aa18edd-5055-40c5-94dd-302068721b26"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("4a90bfd5-1763-42a9-b776-5b8b2937a2ab"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("ad7a93e1-3602-4fe2-959d-2bb626cfb882"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("4ef158e8-bd9c-415c-92bf-99495521bbe3"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("cfe6574d-989d-4ef9-b949-4c266715b912"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("c3d0d27b-14c3-42e6-b412-104138b41ad0"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("87b3d6c9-20f9-40d2-ad41-5502ad335671"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("440aeec9-33ef-4866-a6af-9ec4b0cac22e"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("9901c235-5f88-4644-81ab-27b3b2ff9364"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("98b1fe32-29fa-4d8c-84e6-91bb63b4370d"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("29436514-e9d5-4477-b72f-22369927c456"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("425dc878-d283-4a71-b5ba-8c40a8a82819"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3d00f3af-30f2-48aa-9a45-07333d9ac9ea"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("65a349c1-0395-47f7-a272-53e99971304f"),
                            Name = "Saul Rodriguez",
                            SchoolId = new Guid("a5c63668-6dd7-421a-98f7-795862054eea"),
                            Score = 95
                        },
                        new
                        {
                            StudentId = new Guid("aaed901b-aee6-4da9-aab7-1f82cbd07339"),
                            Name = "Felipe Gonzalez",
                            SchoolId = new Guid("a5c63668-6dd7-421a-98f7-795862054eea"),
                            Score = 92
                        },
                        new
                        {
                            StudentId = new Guid("44e2df3b-ebbb-4a50-890e-02cb2ac2578e"),
                            Name = "Alberto Medina",
                            SchoolId = new Guid("a5c63668-6dd7-421a-98f7-795862054eea"),
                            Score = 77
                        },
                        new
                        {
                            StudentId = new Guid("78f4c612-58db-4893-b373-b1884571425d"),
                            Name = "Pedro Jimenez",
                            SchoolId = new Guid("69636bb0-c211-4e83-bbed-d6b7682bd6c9"),
                            Score = 87
                        },
                        new
                        {
                            StudentId = new Guid("754823d0-6848-4ad5-909b-c3bd229617b2"),
                            Name = "Samanta Lopez",
                            SchoolId = new Guid("69636bb0-c211-4e83-bbed-d6b7682bd6c9"),
                            Score = 75
                        },
                        new
                        {
                            StudentId = new Guid("60946ab3-0ecf-4e3c-bcd1-34d989fe12b5"),
                            Name = "Francisco Mendoza",
                            SchoolId = new Guid("69636bb0-c211-4e83-bbed-d6b7682bd6c9"),
                            Score = 54
                        },
                        new
                        {
                            StudentId = new Guid("32a64337-4a2f-4c7b-8c51-e57d4053699e"),
                            Name = "Santiago Ojeda",
                            SchoolId = new Guid("ed5331c6-3cef-46b3-9b34-c23a19dccc80"),
                            Score = 90
                        },
                        new
                        {
                            StudentId = new Guid("7ba8e0b1-f626-432e-9ddd-3867c17756b9"),
                            Name = "Raul Farias",
                            SchoolId = new Guid("ed5331c6-3cef-46b3-9b34-c23a19dccc80"),
                            Score = 86
                        },
                        new
                        {
                            StudentId = new Guid("421e86c5-1781-45c3-93f7-3dd172e22f6f"),
                            Name = "Manuel Lopez",
                            SchoolId = new Guid("ed5331c6-3cef-46b3-9b34-c23a19dccc80"),
                            Score = 80
                        },
                        new
                        {
                            StudentId = new Guid("69b2368b-0387-4b47-a93a-2ef14043d2ca"),
                            Name = "Guadalupe Ortiz",
                            SchoolId = new Guid("4172f41d-f7a3-4db9-bdb3-4b7709a31831"),
                            Score = 70
                        },
                        new
                        {
                            StudentId = new Guid("3012ca8a-dd46-4e80-abe1-e2fb083f653b"),
                            Name = "Cristina Gutierrez",
                            SchoolId = new Guid("4172f41d-f7a3-4db9-bdb3-4b7709a31831"),
                            Score = 96
                        },
                        new
                        {
                            StudentId = new Guid("83340d01-954d-44a6-b6ff-a399676c0ec1"),
                            Name = "Omar Reyes",
                            SchoolId = new Guid("4172f41d-f7a3-4db9-bdb3-4b7709a31831"),
                            Score = 67
                        },
                        new
                        {
                            StudentId = new Guid("d7804ff3-d242-4593-a424-016cb779b67a"),
                            Name = "Jose Osuna",
                            SchoolId = new Guid("c80f1741-b017-4ff7-87f6-d48c8f326fdc"),
                            Score = 88
                        },
                        new
                        {
                            StudentId = new Guid("00ed3edf-f828-47de-bbaf-9ef93b8720aa"),
                            Name = "Patricia Acosta",
                            SchoolId = new Guid("c80f1741-b017-4ff7-87f6-d48c8f326fdc"),
                            Score = 87
                        },
                        new
                        {
                            StudentId = new Guid("594c387a-43f4-450b-bf05-0ef2e1436dfd"),
                            Name = "Alma Lopez",
                            SchoolId = new Guid("c80f1741-b017-4ff7-87f6-d48c8f326fdc"),
                            Score = 94
                        });
                });

            modelBuilder.Entity("ODataProject.Models.Student", b =>
                {
                    b.HasOne("ODataProject.Models.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
