// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ODataProject.Context;

namespace ODataProject.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20190704003907_SeedingData001")]
    partial class SeedingData001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ODataProject.Models.School", b =>
                {
                    b.Property<Guid>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.HasKey("SchoolId");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            SchoolId = new Guid("3bb81861-97df-4bd7-8d61-827734fcd808"),
                            City = "Mexicali",
                            Name = "UABC - Mexicali",
                            State = "Baja California"
                        },
                        new
                        {
                            SchoolId = new Guid("b86554c5-6789-411f-ab51-1e01da7ba33d"),
                            City = "Mexicali",
                            Name = "TECNOLOGICO UNIVERSIDAD - Mexicali",
                            State = "Baja California"
                        },
                        new
                        {
                            SchoolId = new Guid("833c3346-fa7b-40a7-a6e0-745cf6006ed7"),
                            City = "Ensenada",
                            Name = "UABC - Ensenada",
                            State = "Baja California"
                        },
                        new
                        {
                            SchoolId = new Guid("f1a55daa-8417-47ea-9b83-04f63c4cf8d8"),
                            City = "Mexicali",
                            Name = "XOCHICALCO UNIVERSIDAD - Mexicali",
                            State = "Baja California"
                        },
                        new
                        {
                            SchoolId = new Guid("3aea756e-5203-4811-b290-746d392ade83"),
                            City = "Mexicali",
                            Name = "CETYS UNIVERSIDAD - Mexicali",
                            State = "Baja California"
                        },
                        new
                        {
                            SchoolId = new Guid("39cf30b9-ddc1-48de-a24a-f408ca7c5179"),
                            City = "Tijuana",
                            Name = "CETYS UNIVERSIDAD - Tijuana",
                            State = "Baja California"
                        });
                });

            modelBuilder.Entity("ODataProject.Models.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<Guid>("SchoolId");

                    b.Property<int>("Score");

                    b.HasKey("StudentId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("dbda2ce8-5611-4273-a64f-be6d6c4c1f10"),
                            Name = "Jorge Apodaca",
                            SchoolId = new Guid("3bb81861-97df-4bd7-8d61-827734fcd808"),
                            Score = 100
                        },
                        new
                        {
                            StudentId = new Guid("04f4a022-04c9-42a4-973a-755d0c0b767d"),
                            Name = "Claudia Rosales",
                            SchoolId = new Guid("3bb81861-97df-4bd7-8d61-827734fcd808"),
                            Score = 85
                        },
                        new
                        {
                            StudentId = new Guid("5d8979de-44f0-41f5-8dc1-e3aad107f682"),
                            Name = "Ricardo Beltran",
                            SchoolId = new Guid("3bb81861-97df-4bd7-8d61-827734fcd808"),
                            Score = 89
                        },
                        new
                        {
                            StudentId = new Guid("2f8053cb-e6fb-4400-a575-79136994f942"),
                            Name = "Saul Rodriguez",
                            SchoolId = new Guid("b86554c5-6789-411f-ab51-1e01da7ba33d"),
                            Score = 95
                        },
                        new
                        {
                            StudentId = new Guid("d659adc7-2b2e-41d9-b783-f86e27ca2540"),
                            Name = "Felipe Gonzalez",
                            SchoolId = new Guid("b86554c5-6789-411f-ab51-1e01da7ba33d"),
                            Score = 92
                        },
                        new
                        {
                            StudentId = new Guid("e742406e-6e5f-495f-b375-587234b3302f"),
                            Name = "Alberto Medina",
                            SchoolId = new Guid("b86554c5-6789-411f-ab51-1e01da7ba33d"),
                            Score = 77
                        },
                        new
                        {
                            StudentId = new Guid("77739b69-cabd-4275-9bbc-d770add33272"),
                            Name = "Pedro Jimenez",
                            SchoolId = new Guid("833c3346-fa7b-40a7-a6e0-745cf6006ed7"),
                            Score = 87
                        },
                        new
                        {
                            StudentId = new Guid("e3fc4cd8-d773-48d9-85d4-f2f8c93cc345"),
                            Name = "Samanta Lopez",
                            SchoolId = new Guid("833c3346-fa7b-40a7-a6e0-745cf6006ed7"),
                            Score = 75
                        },
                        new
                        {
                            StudentId = new Guid("6d2eefec-d6dd-453c-b100-92668496cac8"),
                            Name = "Francisco Mendoza",
                            SchoolId = new Guid("833c3346-fa7b-40a7-a6e0-745cf6006ed7"),
                            Score = 54
                        },
                        new
                        {
                            StudentId = new Guid("582b4746-3ad2-42c4-b408-de1692e1cc2c"),
                            Name = "Santiago Ojeda",
                            SchoolId = new Guid("f1a55daa-8417-47ea-9b83-04f63c4cf8d8"),
                            Score = 90
                        },
                        new
                        {
                            StudentId = new Guid("5baca2fc-f61e-43b0-b934-27c39d5f4642"),
                            Name = "Raul Farias",
                            SchoolId = new Guid("f1a55daa-8417-47ea-9b83-04f63c4cf8d8"),
                            Score = 86
                        },
                        new
                        {
                            StudentId = new Guid("3380e0a1-1d3b-4dc8-a429-9ad5471c8ba0"),
                            Name = "Manuel Lopez",
                            SchoolId = new Guid("f1a55daa-8417-47ea-9b83-04f63c4cf8d8"),
                            Score = 80
                        },
                        new
                        {
                            StudentId = new Guid("4a424406-82b3-49d1-8c18-e4effb717c9a"),
                            Name = "Guadalupe Ortiz",
                            SchoolId = new Guid("3aea756e-5203-4811-b290-746d392ade83"),
                            Score = 70
                        },
                        new
                        {
                            StudentId = new Guid("2f428cd4-4799-409f-98d2-256e8e669138"),
                            Name = "Cristina Gutierrez",
                            SchoolId = new Guid("3aea756e-5203-4811-b290-746d392ade83"),
                            Score = 96
                        },
                        new
                        {
                            StudentId = new Guid("e2b702bb-5ce4-4c32-9d47-200ea3a6c0d7"),
                            Name = "Omar Reyes",
                            SchoolId = new Guid("3aea756e-5203-4811-b290-746d392ade83"),
                            Score = 67
                        },
                        new
                        {
                            StudentId = new Guid("97dedf40-0ea1-46b1-95ca-51d1c923262a"),
                            Name = "Jose Osuna",
                            SchoolId = new Guid("39cf30b9-ddc1-48de-a24a-f408ca7c5179"),
                            Score = 88
                        },
                        new
                        {
                            StudentId = new Guid("a3d563cd-a358-408c-aa73-238917489bae"),
                            Name = "Patricia Acosta",
                            SchoolId = new Guid("39cf30b9-ddc1-48de-a24a-f408ca7c5179"),
                            Score = 87
                        },
                        new
                        {
                            StudentId = new Guid("244ddff1-22b2-414c-800a-621543d5794d"),
                            Name = "Alma Lopez",
                            SchoolId = new Guid("39cf30b9-ddc1-48de-a24a-f408ca7c5179"),
                            Score = 94
                        });
                });

            modelBuilder.Entity("ODataProject.Models.Student", b =>
                {
                    b.HasOne("ODataProject.Models.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
